## this file is used to deploy the SmartShop application to an EC2 instance using GitHub Actions. It triggers on pushes to the main branch and uses SSH to connect to the EC2 instance, pull the latest code, and restart the Docker containers.###

name: Deploy SmartShop to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd "$HOME/-SmartShop_AI"
            git pull origin main
            sudo docker compose up -d --build
